# Schedule testing task
# https://docs.github.com/cn/actions/using-workflows/events-that-trigger-workflows#schedule
# Please set SENDER_MNEMONIC, SLACK_WEBHOOK_URL in github secrets.

name: Cron testing

on:
  schedule:
    # Please set the start time (UTC time zone).
    # https://docs.github.com/cn/actions/using-workflows/events-that-trigger-workflows#schedule
    # - cron: '0 12 * * MON-FRI'
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: |
            npm install
            npm ci

      - name: Run test
        env:
          SENDER_MNEMONIC: ${{ secrets.SENDER_MNEMONIC }}
        run: |
          npm run test

  report-failure:
    name: Report failure status
    needs: [test]
    if: failure()

    runs-on: ubuntu-20.04

    steps:
      - name: Check workflow status
        id: check-workflow-status
        uses: martialonline/workflow-status@v2

      - name: Report to slack
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ steps.check-workflow-status.outputs.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
