name: Update dev tag to latest

on:
  workflow_dispatch:
    inputs:
      trigger-manual:
        description: 'Manually trigger the workflow'

jobs:
  update-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: ðŸ” Authenticate with NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTOMATION_TOKEN_CHRIS }}" > ~/.npmrc

      - name: Set package names
        id: set_package_names
        run: |
          echo '["@oak-network/api-augment", "@oak-network/types"]' > packages.json

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Loop through Package Names
        id: loop-package-names
        run: |
          packages=$(cat packages.json)
          for package in $packages; do
            echo "Processing package: $package"

            # Get dev version
            dev_version=$(npm show $package@dev version)
            echo "Dev version: $dev_version"

            # Set latest tag
            npm dist-tag add $package@$dev_version latest --registry=https://registry.npmjs.org/
            echo "Latest tag set to $dev_version"

          done
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN_CHRIS }}
          
      - name: Use loop outputs
        run: |
          echo "Loop completed."
