name: Update dev tag to latest

on:
  workflow_dispatch:
    inputs:
      trigger-manual:
        description: 'Manually trigger the workflow'

jobs:
  update-tags:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            package:
              # List the packages to run here. The matrix will run one job for each package parallelly. 
              - api-augment
              - types

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: ðŸ” Authenticate with NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTOMATION_TOKEN_CHRIS }}" > ~/.npmrc

      - name: Get dev version of ${{ matrix.package }}
        id: get-version
        run: |
          dev_version=$(npm show @oak-network/${{ matrix.package }}@dev version)
          echo "Dev version: $dev_version"
          echo "dev_version=$dev_version" >> $GITHUB_OUTPUT
      
      - name: Point latest tag to ${{ steps.get-version.outputs.dev_version }
        run: |
          npm dist-tag add @oak-network/${{ matrix.package }}@${{ steps.get-version.outputs.dev_version }} latest --registry=https://registry.npmjs.org/
          echo "Latest tag set to ${{ steps.get-version.outputs.dev_version }}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN_CHRIS }}